"""Mock grants for --mock --dry-run offline testing. No API calls made."""


def get_grants():
    return [
        {
            "funder": "New York Foundation for the Arts",
            "title": "NYFA Artists' Fellowship — Visual Arts",
            "description": "Biennial fellowship supporting New York State visual artists with unrestricted funds to advance their work. Open to painters, sculptors, and installation artists. No project deliverables required.",
            "url": "https://www.nyfa.org/awards-grants/artists-fellowships/",
            "award_amount": "$7,000",
            "deadline": "2026-08-15",
            "eligibility": "New York State residents only. Individual artists. No students currently enrolled in degree programs.",
            "disciplines": ["visual art", "painting", "sculpture", "installation"],
            "org_types": ["individual"],
            "location": "New York State",
            "source": "mock",
            "mock_score": 91,
        },
        {
            "funder": "National Endowment for the Arts",
            "title": "Grants for Arts Projects — Music",
            "description": "Supports the creation, engagement, sustainment, or livelihood of artists and arts professionals working in music. Organizations and individual artists at all career stages are eligible.",
            "url": "https://www.arts.gov/grants/grants-for-arts-projects",
            "award_amount": "$10,000 – $100,000",
            "deadline": "2026-07-10",
            "eligibility": "US-based nonprofit organizations with 501(c)(3) status or units of state or local government. Individual artists must apply through a fiscal sponsor.",
            "disciplines": ["music", "performance"],
            "org_types": ["nonprofit", "collective"],
            "location": "National",
            "source": "mock",
            "mock_score": 74,
        },
        {
            "funder": "Lambent Foundation",
            "title": "Community Organizing Arts Fund",
            "description": "Unrestricted grants for NYC-based organizations using arts and culture as a tool for community organizing, social justice, and civic engagement. Prioritizes BIPOC-led organizations.",
            "url": "https://lambentfoundation.org/grants",
            "award_amount": "$15,000 – $25,000",
            "deadline": "Rolling",
            "eligibility": "NYC-based nonprofits and fiscally sponsored collectives. Must demonstrate community organizing focus. Priority to BIPOC-led groups.",
            "disciplines": ["community organizing", "visual art", "performance", "multidisciplinary"],
            "org_types": ["nonprofit", "collective"],
            "location": "NYC",
            "source": "mock",
            "mock_score": 88,
        },
        {
            "funder": "Academy of American Poets",
            "title": "Poets & Writers — Readings & Workshops",
            "description": "Supports poets running community-based workshops, readings, and residencies. Funds can cover artist fees, materials, venue, and documentation.",
            "url": "https://www.poets.org/grants",
            "award_amount": "$1,000 – $5,000",
            "deadline": "2026-09-01",
            "eligibility": "Individual poets and nonprofit literary organizations. Open nationally. Must have published at least one collection or chapbook.",
            "disciplines": ["writing", "poetry", "community organizing"],
            "org_types": ["individual", "nonprofit"],
            "location": "National",
            "source": "mock",
            "mock_score": 62,
        },
        {
            "funder": "Foundation for Contemporary Arts",
            "title": "Emergency Grants — Dance",
            "description": "Emergency funding for dance artists facing unexpected opportunities or expenses. Fast-turnaround grants for choreographers and independent dance artists who need support within weeks.",
            "url": "https://www.foundationforcontemporaryarts.org/grants/emergency-grants/",
            "award_amount": "Up to $3,000",
            "deadline": "Rolling",
            "eligibility": "Individual dance artists and choreographers. US-based. Must demonstrate urgency and time-sensitivity of the need.",
            "disciplines": ["dance", "performance", "choreography"],
            "org_types": ["individual"],
            "location": "National",
            "source": "mock",
            "mock_score": 55,
        },
    ]
